install:
  - sudo make install

script:
  - make build

before_deploy:
  - git config --local user.name "Borodin Gregory"
  - git config --local user.email "grihabor@gmail.com"
  - git tag $(make tag)

deploy:
  provider: releases
  api_key: "${RELEASES_TOKEN}"
  file: "build/diploma.pdf"
  skip_cleanup: true
  on: 
    branch: master
