install: 
  - sudo make install

script:
  - make build

before_deploy:
  - git config --local user.name "Borodin Gregory"
  - git config --local user.email "grihabor@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key: "${RELEASES_TOKEN}"
  file: "build/diploma.pdf"
  skip_cleanup: true
  on: 
    branch: master
