DIPLOMA_PDF   := diploma.pdf
FLAGS         := -pdfps \
                 -latex="latex -interaction=nonstopmode" \
                 -use-make \
                 -bibtex
                 
.PHONY: all
all: $(DIPLOMA_PDF)

%.tex: %.raw
	./raw2tex $< > $@

%.tex: %.dat
	./dat2tex $< > $@

$(DIPLOMA_PDF): diploma.tex
	latexmk $(FLAGS) diploma.tex

clean:
	latexmk -CA
        